
services:
    configuration:
        class: Accompli\Configuration\Configuration
        calls:
            - [load, ["%configuration.file%"]]
    connection_manager:
        class: Accompli\Deployment\Connection\ConnectionManager
    event_dispatcher:
        class: Accompli\EventDispatcher\EventDispatcher
        calls:
            - [addListener, [accompli.create_connection, ["@connection_manager", onCreateConnection]]]
            - [addSubscriber, ["@log_subscriber"]]
            - [addSubscriber, ["@log_failure_subscriber"]]
            - [addSubscriber, ["@data_collector_subscriber"]]
    logger:
        class: Accompli\Console\Logger\ConsoleLogger
        arguments: ["%console.output_interface%"]

    profiler_data_collector:
        class: Accompli\DataCollector\ProfilerDataCollector
    event_data_collector:
        class: Accompli\DataCollector\EventDataCollector

    log_subscriber:
        class: Accompli\EventDispatcher\Subscriber\LogSubscriber
        arguments: ["@logger"]
    log_failure_subscriber:
        class: Accompli\EventDispatcher\Subscriber\LogFailureSubscriber
        arguments: ["@logger"]
    data_collector_subscriber:
        class: Accompli\EventDispatcher\Subscriber\DataCollectorSubscriber
        arguments: [["@event_data_collector", "@profiler_data_collector"]]
