
services:
    configuration:
        class: Accompli\Configuration\Configuration
        calls:
            - [load, ["%configuration.file%"]]
    connection_manager:
        class: Accompli\Deployment\Connection\ConnectionManager
    event_dispatcher:
        class: Symfony\Component\EventDispatcher\EventDispatcher
    logger:
        class: Symfony\Component\Console\Logger\ConsoleLogger
        arguments: ["%console.output_interface%"]
