
services:
    configuration:
        class: Accompli\Configuration\Configuration
        calls:
            - [load, ["%configuration.file%"]]
    connection_manager:
        class: Accompli\Deployment\Connection\ConnectionManager
    event_dispatcher:
        class: Accompli\EventDispatcher\EventDispatcher
        calls:
            - [addListener, [accompli.create_connection, ["@connection_manager", onCreateConnection]]]
            - [addSubscriber, ["@log_subscriber"]]
            - [addSubscriber, ["@log_failure_subscriber"]]
    logger:
        class: Accompli\Console\Logger\ConsoleLogger
        arguments: ["%console.output_interface%"]
    log_subscriber:
        class: Accompli\EventDispatcher\Subscriber\LogSubscriber
        arguments: ["@logger"]
    log_failure_subscriber:
        class: Accompli\EventDispatcher\Subscriber\LogFailureSubscriber
        arguments: ["@logger"]
