language: php

php:
  - 5.4
  - 5.5

before_script:
  - ./tests/pecl-install.sh
  - composer self-update
  - composer install
  - mkdir -p build/logs

script: vendor/bin/phpunit --coverage-clover build/logs/clover.xml

after_script: vendor/bin/coveralls -v
