language: php

php:
  - 5.4
  - 5.5

before_script:
  - sudo apt-get update -qq
  - sudo apt-get install -y -qq libssh2-1-dev
  - pecl install ssh2-beta < ./tests/.non-interactive
  - composer self-update
  - composer install
  - mkdir -p build/logs

script: vendor/bin/phpunit --coverage-clover build/logs/clover.xml

after_script: vendor/bin/coveralls -v
